### ISSUE TITLE
Parse Error when selecting new field after installation

### ISSUE THREAD

**Issue by goodmixer** [wbrowar/craft-little-layout#1]
Hi Getting syntax error, unexpected 'int' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) when selecting new field after installation. 

Running Craft 3.6.11.2 and php 7.3.8

Is php 7.4 a requirement for little layout to work?

**Comment by wbrowar** [comment]
Hey @goodmixer 7.4 isn't a requirement, so this is a bug. I did intentionally plan to support 7.2.5 as per Craft’s new minimum required version, so I'll do some extra testing to make sure it's compatible back to the minimum version.

Thanks for bringing this to my attention!

Will

**Comment by wbrowar** [comment]
Thanks again, @goodmixer. This should be fixed in [1.0.1](https://github.com/wbrowar/craft-little-layout/releases/tag/1.0.1).

I'd love to hear how you’re using your layout fields, so please consider leaving some feedback in [Discussions](https://github.com/wbrowar/craft-little-layout/discussions).

_- Will_
